builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w
      - -X csv-tools/internal/version.Version={{.Version}}
      - -X csv-tools/internal/version.CommitHash={{.Commit}}
      - -X csv-tools/internal/version.BuildTime={{.Date}}
    main: .
    binary: csv-tools

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
