version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/3-2-1-contact/csv-tools/internal/version.Version={{.Version}}
      - -X github.com/3-2-1-contact/csv-tools/internal/version.CommitHash={{.ShortCommit}}
      - -X github.com/3-2-1-contact/csv-tools/internal/version.BuildTime={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'

release:
  github:
    owner: 3-2-1-contact
    name: csv-tools

  draft: false
  prerelease: auto
  mode: replace

  # If you want to add custom headers to the release notes
  header: |
    ## CSV Tools Release {{.Version}} ({{ .Date }})


  footer: |
    ## Gracias!


signs:
  - artifacts: checksum

brews:
  - name: csvtools
    homepage: "https://github.com/3-2-1-contact/csv-tools"
    description: "Tools for working with CSV files"
    license: "MIT"
    tap:
      owner: 3-2-1-contact
      name: homebrew-tools
    folder: Formula
    install: |
      bin.install "csvtools"
